# Generated by Django 4.2.4 on 2023-08-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labels', models.TextField(max_length=30)),
                ('values', models.IntegerField()),
            ],
        ),
    ]
