# Generated by Django 4.2.4 on 2023-08-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='labels',
            field=models.CharField(max_length=30),
        ),
    ]
