# Generated by Django 4.2.4 on 2023-08-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.CharField(max_length=20)),
                ('product_quantity', models.IntegerField()),
            ],
        ),
    ]
