# Generated by Django 4.2.4 on 2023-08-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstable',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
