# Generated by Django 4.2.4 on 2023-08-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productstable_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstable',
            name='description',
            field=models.TextField(default='description box', max_length=300),
            preserve_default=False,
        ),
    ]
